#!/usr/bin/env bash
os=$(uname)
file=notes.yml
link=current

get_day(){
if [[ $os == "Darwin" ]]; then
	date=$(date -v +Tue +"%Y-%m-%d")
elif [[ $os == "Linux" ]]; then
	date=$(date -d next-tuesday +"%Y-%m-%d")
else
	echo "$os not understood"
fi

if [[ "$date" == "$(date +"%Y-%m-%d")" ]]; then
	date=$(date -v +7d +"%Y-%m-%d")
fi
}

template(){
cat <<EOF > $date/$file
Website: https://lug.acm.illinois.edu/
Meeting Info: See website
Date: $date

Talks:
  - TBA

Next Meeting Topics:
  - TBA (0)
EOF
}

if [ -z $date ]
then
    get_day
fi
if ! [ -d $date ]
then
	mkdir $date && template
	ln -f -s $date/notes.yml current
	[ -f current ] && git add $date current && git commit -m "begin new meeting notes for $date" && git push
else
	echo "Meeting $date already exists"
	exit 1
fi

echo "Run notes.yml through a YAML parser before committing: http://www.yamllint.com/"
